### ISSUE TITLE
ActionServer to execute actions

### ISSUE THREAD

**Issue by marc-hanheide** [pet1330/FInCoR#19]
Implement an [action server](https://github.com/cdondrup/PetriNetPlans/blob/catkinised/PNPros/ROS_bridge/pnp_ros/scripts/PNPActionServer.py) that works on the [PNP action](https://github.com/cdondrup/PetriNetPlans/blob/catkinised/PNPros/ROS_bridge/pnp_msgs/action/PNP.action).

It needs to be able to execute blocksworld actions, such as
- pick-up
- put-down
- stack
- unstack

**Comment by marc-hanheide** [comment]
check it works for any object on the table (objects identified by the ID) by using `actionlib axclient`.

**Comment by pet1330** [comment]
Use action server from #20 not the action server above in PNP.

**Comment by marc-hanheide** [comment]
> Use action server from #20 not the action server above in PNP.

I think these are different things, aren't they?

One component (the one discussed in #20) generates a PNP plan from some sort of planner (e.g. fast-downward). This issue is about writing an action server that executes a PNP plan on the robot. It's true that in #20 @cdondrup discussed the implementation of such action servers, and that his comments partially also apply to this issue, but they are separate issues, aren't they?

**Comment by cdondrup** [comment]
We discussed this today and what we mean by this is to use the `PNPPluginServer` wrappers for the `ActionServer` (as shown in my comment in #20) instead of @pet1330 implementing something like the [example action server](https://github.com/cdondrup/PetriNetPlans/blob/catkinised/PNPros/ROS_bridge/pnp_ros/scripts/PNPActionServer.py) on the PNP ros bridge repo which would require that you do everything in this one component. My plugin server takes care of calling the right action server and does all the communication with the PNP so there is no need to reimplement this.

**Comment by cdondrup** [comment]
So he would implement the grey boxes:

![pnp 001](https://cloud.githubusercontent.com/assets/4293484/17531453/d47ad45e-5e73-11e6-9841-c3d7a8d44b40.jpeg)
