### ISSUE TITLE
Generate a PNP plan from the PDDL output of fast-downward

### ISSUE THREAD

**Issue by marc-hanheide** [pet1330/FInCoR#20]
convert

```
(unstack c a)
(put-down c)
(pick-up b)
(stack b c)
(pick-up a)
(stack a b)
; cost = 6 (unit cost)
```

into a PNP plan. Use [PNPgen](https://github.com/cdondrup/PetriNetPlans/blob/catkinised/PNPgen/src/pnpgen_linear.cpp) (there will be a ROS version by @cdondrup) to generate a PNP. It takes as input something like [`goto_printer|30; say_hello; goto_home|15`](https://github.com/cdondrup/PetriNetPlans/blob/catkinised/PNPgen/test/DIAG_printer.plan), so, e.g.: `unstack_c_a; put-down_c; pick-up_b; stack_b_c; pick-up_a; stack_a_b`

This should be a component like this one (with @cdondrup's new generation server in place):

```
import rospy
from std_msgs.msg import String
from pnp_msgs.srv import PNPGeneratePlan, PNPGeneratePlanRequest


class ROSPlanBridge(object):
    def __init__(self, name):
        rospy.loginfo("Starting '%s'." % name)
        self.pub = rospy.Publisher("/planToExec", String, queue_size=1)
        rospy.Subscriber("plan_topic", ... , self.callback)
        rospy.loginfo("Done.")

    def callback(self, msg):
        plan = ... # Parse msg of planner to format like: action1.1_param|action1.2_param;action2_param_param;
        pnml = self.generate_pnml(plan)
        print "Sending pnml"        
        self.pub.publish(pnml)

    def generate_pnml(self, plan):
        s = rospy.ServiceProxy("/pnpgen_linear/generate_plan", PNPGeneratePlan)
        try:            
            s.wait_for_service(timeout=1.)
            return s(PNPGeneratePlanRequest(plan=plan)).pnml
        except rospy.ROSException:
            if not rospy.is_shutdown():
                rospy.logwarn("Unable to generate PNML, retrying.")          
                return self.generate_pnml(plan)

if __name__ == "__main__":
    rospy.init_node("rosplan_bridge")
    ROSPlanBridge(rospy.get_name())
    rospy.spin()
```

**Comment by cdondrup** [comment]
Exactly, just a word of advice the `-` is a special character to denote conditions. Haven't fully figured that out yet ;) So please avoid using that for now. Also `_` is reserved to separate action names from parameters internally so just use camleCase.

Following a little link collection:
- My petrinet version with the working bridge: https://github.com/cdondrup/PetriNetPlans/tree/plugin_server
- There is a launch file which starts the pnp_node and the plugin_server: https://github.com/cdondrup/PetriNetPlans/blob/plugin_server/PNPros/ROS_bridge/pnp_ros/launch/pnp_ros.launch
- The conversion from string like `goto_printer|30; say_hello; goto_home|15` to a ptri-net plan is here: https://github.com/cdondrup/PetriNetPlans/tree/plugin_server/PNPros/ROS_bridge/pnpgen_ros and needs to be started seprate (for now) `rosrun pnpgen_ros pnpgen_ros_node`. This offers a simple service that takes that string and transforms it into an xml that can then be sent to the `/planToExec` topic as described in the script @marc-hanheide posted above (tip @marc-hanheide if you write your codeblocks, start with `` ` `python` that make the code better readable ;) ).
- The actions like `stack a b` need to be implemented as action servers but have to use the wrapper I wrote to register themselves with the pnp server automatically:
  
  ``` python
  from pnp_plugin_server.pnp_simple_plugin_server import PNPSimplePluginServer
  
  class bla():
  def __init__(self, name):
      self._ps = PNPSimplePluginServer(
          name=name,
          ActionSpec=...,
          execute_cb=...,
          auto_start=False
      )
      ...
      self._ps.start()
      rospy.loginfo("Done")
  ```
  
  They have the same arguments as the action server. Examples can be found here: https://github.com/cdondrup/pnp/tree/master/pnp_plugin_servers. One of the only but major restrictions is that the actions you use can only use datatypes that are directly translatable to python datatypes: e.g. `float64`, `int8`, `string`, `bool`, etc. because there is a lot of magic involved regarding the parameter parsing. So the input of our action servers that are triggered by the net has to rather high-level. I am still in the process of understanding how all of this works internally with the variables so that might change at some point.

**Comment by cdondrup** [comment]
Update:

Things are fully (except for the odd minor feature) working now.

### Action servers

As I have written above, the most important thing is that you can use any kind of action server just make sure you use the wrapper: `PNPPluginServer` or `PNPSimplePluginServer` depending on if you want a full or simple action server. Additionally, if your action server changes the world state and you want to update the knowledge base (described below) from its out put it has to return a specific message type. A short working example would be:

``` python
#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 22 13:12:27 2016
@author: cd32
"""

import rospy
from pnp_plugin_server.pnp_simple_plugin_server import PNPSimplePluginServer
from pnp_msgs.msg import ActionResult
from my_pkg.msg import MyAction, MyResult


class MyServer(object):
    def __init__(self):
        self._ps = PNPSimplePluginServer(
            name="pickUp",
            ActionSpec=MyAction,
            execute_cb=self.execute_cb,
            auto_start=False
        )
        self._ps.start()

    def execute_cb(self, goal):
        # Assuming you pick up block a from the table and put it on b

        res = MyResult()
        res.result.append(ActionResult(cond="on__b__a", truth_value=ActionResult.TRUE))
        res.result.append(ActionResult(cond="on_table__a", truth_value=ActionResult.FALSE))
        self._ps.set_succeeded(res)

if __name__ == "__main__":
    rospy.init_node("say")
    s = MyServer()
    rospy.spin()
```

And you `My.action` has to look like this:

```
# Goal params (only basic datatypes like string, float64, int32, etc.)
---
pnp_msgs/ActionResult[] result
---
# Feedback params
```

If you don't have a result, the KB will not be updated. This action server is then called automatically and its result is parsed automatically. If it does not return `success`, error handling comes in (explained below). Examples of this are in the [example package](https://github.com/cdondrup/PetriNetPlans/tree/plugin_server_tmp/PNPros/example/py_simple).

### Knowledge Base

The KB is up to you, doesn't matter if you use mongodb or something else, the only thing you have to do is to implement a simple python class that communicates with it. To make thing easier, you can inherit from the [abstract class](https://github.com/cdondrup/PetriNetPlans/blob/plugin_server_tmp/PNPros/ROS_bridge/pnp_ros/src/pnp_knowledgebase/pnp_knowledgebase_abstractclass.py). The two functions you have to implement are:

``` python
@abstractmethod
    def query_knowledgbase(self, predicate):
        """querry the knowledge base.
        :param predicate: The condition as a string taken from the PNP.
        :return (int) -1 (unknown), 0 (false), or 1 (true)
        """
        return

    @abstractmethod
    def update_knowledgebase(self, predicate, truth_value):
        """update the knowledge base.
        :param predicate: The condition as a string taken from the PNP.
        :param truth_value: (int) -1 (unknown), 0 (false), 1 (true)
        """
        return
```

Where the input predicate from the example action server would be `on__b__a` and `on_table__a`. The truth value is either 0 or 1 where -1 is used as unknown. I would avoid -1 because this is treated the same as 1 by the PNP :( The rest of the magic is done automatically. It offers two services: `/PNPConditionEval` for queries and `~update_knowledgebase` for updates. Even though `~update_knowledgebase` is a private service, it does not matter which name your node has because the service is identified by its type. So `/foo/update_knowledgebase` or `/foo/bar/update_knowledgebase` are all fine. An example of how to use this with a simple dictionary is given in the [minimal knowledgebase](https://github.com/cdondrup/PetriNetPlans/blob/plugin_server_tmp/PNPros/ROS_bridge/pnp_ros/scripts/minimal_knowledgebase.py) which either starts empty or reads knowledge from a yaml file.

### Generating a PNP

The generation process has become a bit more complicated than then one described by @marc-hanheide  but also gives you much more freedom. Once again there is an [abstract class](https://github.com/cdondrup/PetriNetPlans/blob/plugin_server_tmp/PNPros/ROS_bridge/pnpgen_ros/src/pnpgen_ros/pnpgen_bridge_abstractclass.py) that does all the magic in the background and offers quite a few helper functions. The only function you have to implement in the child class is:

``` python
@abstractmethod
    def parse_plan_msg(self, msg):
        """Parse the incoming plan.
        :return pnpgen_ros/Plan
        """
        return
```

A minimum working example is given in [minimal_bridge.py]() which is this:

``` python
#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 28 11:06:58 2016
@author: Christian Dondrup
"""

import rospy
from pnpgen_ros.pnpgen_bridge_abstractclass import PNPGenBridgeAbstractclass
from std_msgs.msg import String
import json


class MinimalBridge(PNPGenBridgeAbstractclass):
    def __init__(self, name):
        rospy.loginfo("Starting '%s'." % name)
        super(MinimalBridge, self).__init__()
        rospy.Subscriber("~plan", String, self.callback)
        rospy.loginfo("Done.")

    def callback(self, msg):
        msg = json.loads(msg.data)
        self.generate_and_send_pnml(msg) # This function uses 'parse_plan_msg' to generate the plan and then publishes it on the correct topic '/planToExec'
        rospy.loginfo("Sending pnml")

    def parse_plan_msg(self, msg):
        plan = self.new_plan() # Helper function to get a new plan object
        for step in msg["action_sequence"]:
            plan.actions.append(self.new_action_list( # Helper function to get a new list of actions that are supposed to be concurrent
                actions=[self.new_action( # Helper function to generate a new atomic action (Like the actions server above)
                        name=str(action["name"]),
                        duration=int(action["duration"]),
                        parameters=[str(param) for param in action["parameters"]]
                    ) for action in step["concurrent_actions"]]
                )
            )
        # Execution rules are the error handling
        plan.execution_rules = self.new_execution_rule_list( # Helper function to create new execution rule list
            rules=[self.new_execution_rule( # Helper function to create new execution rule
                    timing=int(rule["timing"]), # before: 0, during: 1, or after: 2
                    action_name=str(rule["action"]), # the action it applies for
                    condition=str(rule["condition"]), # the condition when it should be activated
                    recovery=self.new_action_list(actions=[self.new_action( # The actions to be executed as a recovery behaviour
                        name=str(x["name"]),
                        duration=int(x["duration"]),
                        parameters=[str(y) for y in x["parameters"]]
                    ) for x in rule["recovery"]]
                )
            ) for rule in msg["execution_rules"]]
        )
        return plan

if __name__ == "__main__":
    rospy.init_node("minimal_gen_bridge")
    MinimalBridge(rospy.get_name())
    rospy.spin()
```

This minimal bridge is triggered by the [very basic "planner"](https://github.com/cdondrup/PetriNetPlans/blob/plugin_server_tmp/PNPros/ROS_bridge/pnpgen_ros/scripts/read_json_plan.py) which just reads this json plan:

```
{
  "action_sequence":
    [
      {"concurrent_actions":
        [
          {"name": "goto", "parameters": ["close", "far"], "duration": 5}
        ]
      },
      {"concurrent_actions":
        [
          {"name": "say", "parameters": ["hello", "close"], "duration": 2}
        ]
      }
    ],
  "execution_rules":
    [
      {"timing": 2, "action": "goto", "condition": "(not robot_at__close)", "recovery": [{"name": "restart_action", "parameters": [], "duration": 0}]}
    ]
}
```

So a plan is an action_sequence where each entry in the list is another list of concurrent actions that ar running at the same time. In above case, there is no concurrency so we just execute `goto` and `say` after each other. As execution rules we define that `after` the `goto` action if the condition `(not robot_at__close)` is true, the actions should be restarted. `restart_action` is a special key word which is not expected to be an action server which is why it does not have parameters or a duration either. Btw. if duration is >0 the action will be terminated if the time is up.

### Error handling

There are a few specific key words that one needs to know:
- Conditions: every logical expression like `(and (not on__a__b) on_table__a)` is valid or the special key word `action_failed` can be used which is triggered if the action server does not report success.
- Recovery: Can be a list of actions (no concurrency allowed for now) and/or special keywords: `restart_action`, `skip_action`, `fail_plan`, `restart_plan`. So an example would be `goto_foo, say_bla, restart_action`. There are [helper functions](https://github.com/cdondrup/PetriNetPlans/blob/plugin_server_tmp/PNPros/ROS_bridge/pnpgen_ros/src/pnpgen_ros/pnpgen_bridge_abstractclass.py#L24-L28) to easily create them for your plan creation.

An example of how this works for ROSPlan can be found here: https://github.com/cdondrup/pnp/tree/master/rosplan_pnp_bridge

Also, If you want to start the system just use [this launch file](https://github.com/cdondrup/PetriNetPlans/blob/plugin_server_tmp/PNPros/ROS_bridge/pnp_ros/launch/pnp_ros.launch) without any parameters and run the minimal knowledge base and the minimal bridge. The you can run the planner that reads from the json file. If you want to run it with the test action servers, run [this launch file](https://github.com/cdondrup/PetriNetPlans/blob/plugin_server_tmp/PNPros/example/py_simple/launch/py_simple.launch).

**Comment by cdondrup** [comment]
There is also [a helper function to create conditions](https://github.com/cdondrup/PetriNetPlans/blob/plugin_server_tmp/PNPros/ROS_bridge/pnpgen_ros/src/pnpgen_ros/utils.py#L21-L35) which is just called like:

``` python
create_condition(AND, create_condition(NOT, "on__a__b"), "on_table__a")
```

which creates: `(and (not on__a__b) on_table__a)`. This seems a bit of an overkill but it also takes lists of strings so it makes it easy to automate the process. Also 

``` python
create_condition(AND, ["on_table__a"])
```

returns: `on_table__a` because `(and on_table__a)` breaks the parser because it only has one argument. So you can put in any number of strings or number of lists of strings.

``` python
create_condition(AND, ["on_table__a"], ["bla", "foo"], "spam")
```

**Comment by cdondrup** [comment]
Mind you, there are some issue still left to solve with the pnp in general: https://github.com/iocchi/PetriNetPlans/issues
